In [2]:
import numpy as np

## Creating Numpy Arrays from Python List

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
[3.14, 4, 2, 3]

[3.14, 4, 2, 3]

In [5]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [6]:
np.array([1,2,3,4], dtype = "float32")

array([1., 2., 3., 4.], dtype=float32)

In [7]:
a1 = np.array([1,2,3])
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1,2,3],
             [4,5,6]])
type(a2)

numpy.ndarray

In [10]:
a2.shape

(2, 3)

In [11]:
a2.ndim

2

In [12]:
a2.dtype

dtype('int32')

In [13]:
a2.size

6

## Creating Numpy Arrays from Scratch

### zeros, ones, full, arange, linspace

In [19]:
np.zeros([2,4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
np.ones([3,5], dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
np.full([3,5], 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [25]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### random

In [33]:
#Seed for reproducibility
np.random.seed(0)
np.random.random([4,4])

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [29]:
np.random.random((4,4))

array([[0.36441833, 0.20523707, 0.27245998, 0.83645671],
       [0.54866906, 0.78758677, 0.60107467, 0.57008803],
       [0.28900187, 0.28305359, 0.39814318, 0.88603534],
       [0.05389326, 0.77282884, 0.75400206, 0.12662082]])

In [35]:
np.random.normal(0,1,[3,3])

array([[-0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252]])

In [38]:
np.random.randint(0,10,[4,5])

array([[4, 8, 4, 3, 7],
       [5, 5, 0, 1, 5],
       [9, 3, 0, 5, 0],
       [1, 2, 4, 2, 0]])

In [48]:
np.random.rand(4,4)

array([[0.71530476, 0.89212127, 0.62364682, 0.89487877],
       [0.15100465, 0.68100841, 0.88045553, 0.57460375],
       [0.33718302, 0.63668305, 0.28371643, 0.36216102],
       [0.04793272, 0.83357681, 0.01782431, 0.59710206]])

## Array Indexing & Slicing

### One-dimensional subarray

In [57]:
x1 = np.random.randint(20,size = 6)

In [58]:
x1

array([19,  4, 17,  0,  1, 14])

In [59]:
x1[4], x1[0], x1[-1]

(1, 19, 14)

### Multi-dimensional array

In [60]:
x2 = np.random.randint(10, size = (3,4))

In [61]:
x2

array([[4, 2, 6, 1],
       [0, 1, 4, 1],
       [5, 5, 0, 6]])

In [64]:
x2[1,2] = 6

In [65]:
x2

array([[4, 2, 6, 1],
       [0, 1, 6, 1],
       [5, 5, 0, 6]])

### Slicing:

In [66]:
x1

array([19,  4, 17,  0,  1, 14])

In [67]:
x1[0:3]

array([19,  4, 17])

In [68]:
x1[2:4]

array([17,  0])

In [69]:
x1[::2]

array([19, 17,  1])

In [71]:
 x2[:2,:3]

array([[4, 2, 6],
       [0, 1, 6]])

In [73]:
x2[:,:2]

array([[4, 2],
       [0, 1],
       [5, 5]])

## Reshaping of Arrays & Transpose

In [76]:
grid = np.arange(1,10)
grid.shape

(9,)

In [77]:
grid.reshape([3,3])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
x = np.array([1,2,3])

In [80]:
x.shape

(3,)

In [82]:
x.reshape([1,3]).shape

(1, 3)

In [92]:
x = np.array([[1.,2.],[3.,4.]])

In [93]:
x

array([[1., 2.],
       [3., 4.]])

In [95]:
x.T

array([[1., 3.],
       [2., 4.]])

## Arrays Concatenation and Splitting

In [96]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [97]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [99]:
grid = np.array([[1,2,3],
                [4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
np.concatenate((grid,grid))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [103]:
np.concatenate((grid,grid), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [104]:
x = np.array([1,2,3])

grid = np.array([[9,8,7],
                [6,5,4]])

In [109]:
np.vstack((x,grid)) # vertical

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [110]:
y = np.array([[99],
             [12]])

np.hstack((y,grid)) # horizontal

array([[99,  9,  8,  7],
       [12,  6,  5,  4]])

### Splitting of Arrays

In [111]:
x = np.array([1,2,3,4,5,6,7,8,9])

In [114]:
x1, x2, x3 = np.split(x, [3,5])

In [116]:
x1

array([1, 2, 3])

In [117]:
x2

array([4, 5])

In [118]:
x3

array([6, 7, 8, 9])

## Broadcasting and Vectorized operations

In [120]:
a = np.arange(3)
a

array([0, 1, 2])

In [122]:
a + 5

array([5, 6, 7])

In [124]:
b = np.ones([3,3])
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [125]:
a.shape, b.shape

((3,), (3, 3))

In [126]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [129]:
c = np.arange(3).reshape([3,1])
c

array([[0],
       [1],
       [2]])

In [130]:
a + c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## Manipulating and Comparing Arrays

### Aggregation = performing the same operation on a number of things

In [132]:
list_number = [1,2,3]

In [134]:
ll = np.array(list_number)

In [136]:
ll

array([1, 2, 3])

In [137]:
sum(ll)

6

In [138]:
np.sum(ll)

6

In [141]:
# Create a massive Numpy Array
massive_array = np.random.random(10000)
massive_array[:5]
massive_array.shape

(10000,)

In [142]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

602 µs ± 42.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
5.97 µs ± 318 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [143]:
np.mean(massive_array)

0.5031865876641398

In [144]:
np.max(massive_array)

0.9999976049374766

In [145]:
np.min(massive_array)

9.008123726217399e-05

In [146]:
dog_height = [600, 470, 170, 430, 300]
dog_height = np.array(dog_height)

np.std(dog_height)

147.32277488562318

In [147]:
np.var(dog_height)

21704.0

In [149]:
np.sqrt(np.var(dog_height))

147.32277488562318

## Sorting Arrays
### np.sort use quicksort algorithm

In [154]:
x = np.array([8,234,546,423,2,2,65,456,2])
np.sort(x)

array([  2,   2,   2,   8,  65, 234, 423, 456, 546])

In [155]:
# a related function is argsort, which instead returns the indices of a multidimensional array using the axis argument
np.argsort(x)

array([4, 5, 8, 0, 6, 1, 3, 7, 2], dtype=int64)

## Sorting along rows and columns

In [156]:
np.random.seed(42)
MatA = np.random.randint(0,10, size = (4,6))

In [157]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [158]:
np.sort(MatA, axis = 0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [159]:
np.sort(MatA, axis = 1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## Linear Algebra

In [161]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [162]:
B = np.array([[6,5],
              [4,3],
              [2,1]])

In [163]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [164]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [165]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

### Dot product example

In [3]:
# Number of jars sold
np.random.seed(0)
sale_amounts = np.random.randint(20, size=(5,3))

In [4]:
sale_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [5]:
# Create weekly_sales dataFrame
import pandas as pd

In [10]:
weekly_sales = pd.DataFrame(sale_amounts, index = ["Mon","Tues","Wed","Thurs","Fri"],
                           columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [11]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [9]:
# create a price array
price = np.array([10,8,12])

In [23]:
butter_price = pd.DataFrame(price.reshape([1,3]), index = ["Price"], columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"] )

In [24]:
butter_price

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [25]:
weekly_sales.shape, butter_price.shape

((5, 3), (1, 3))

In [28]:
total_prices = weekly_sales.dot(butter_price.T)
total_prices

Price
Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142

In [29]:
weekly_sales["Total Price"] = total_prices
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total Price
Mon               12             15              0          240
Tues               3              3              7          138
Wed                9             19             18          458
Thurs              4              6             12          232
Fri                1              6              7          142